name: Xiaoyun Daily Broadcast

on:
  schedule:
    # 每天馬來西亞/新加坡/中國/台灣時間早上 5 點執行
    # GitHub Actions 的 cron 使用 UTC 時間。
    # (UTC+8) 早上 5 點是 UTC 時間的前一天晚上 21:00。
    # 分鐘 小時 日 月 星期幾
    - cron: '0 21 * * *'
  workflow_dispatch: # 允許手動從 Actions 分頁觸發，方便測試

jobs:
  broadcast-daily-message:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # 稍微增加超時時間，因為有多次 API 調用

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 建議使用一個較新的穩定版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Xiaoyun's daily broadcast script
        env:
  LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
  PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }} # <--- 確認這裡的 PEXELS_API_KEY
        run: python daily_broadcast.py
